import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { TooltipProvider } from "@/components/ui/tooltip";
import Header from "@/components/header";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "rumia.moe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased prose prose-rumia bg-(--color-background-dark)`}
      >
        <TooltipProvider>
          <Header />
          <div className="w-screen">
            <div className="w-full max-w-(--view-width) mx-auto p-12">
              {children}
            </div>
          </div>
        </TooltipProvider>
      </body>
    </html>
  );
}
